### ISSUE TITLE
Link to pypi is broken and add Install instructions

### ISSUE THREAD

**Issue by fmorato** [kolypto/py-miracle#2]
Hi,

The link to pypi in the github project description is broken and can't just install with `pip install miracle`.

Looking it up on `setup.py`, package name is actually `miracle-acl`, which then works alright.

As the package name is different from repo name and different from pypi package, it'd be great to have install instructions.

**Comment by kolypto** [comment]
Thank you! Closed with a9cec3f74ba2c504bf123ef66bfc674a10203442 .
